[build-system]
requires = ["setuptools>=42", "wheel", "cibuildwheel", "numpy", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "islamic_times/_version.py"