"""Region and city presets for crescent-visibility mapping."""

from __future__ import annotations

CITIES_WORLD: list[str] = [
    "Honolulu",
    "Vancouver",
    "Los Angeles",
    "Mexico City",
    "Toronto",
    "Miami",
    "Washington,  D.C.",
    "Lima",
    "Bogota",
    "Santiago",
    "São Paulo",
    "Dakar",
    "Lagos",
    "Madrid",
    "London",
    "Vienna",
    "Moscow",
    "Cape Town",
    "Istanbul",
    "Cairo",
    "Makkah",
    "Tehran",
    "Nairobi",
    "Addis Ababa",
    "Islamabad",
    "Mumbai",
    "Bangkok",
    "Singapore",
    "Hong Kong",
    "Beijing",
    "Tokyo",
    "Sydney",
    "Perth",
]

CITIES_IRAN: list[str] = [
    "Tehran",
    "Mashhad",
    "Kerman",
    "Shiraz",
    "Zanjan",
    "Ardabil",
    "Isfahan",
    "Gorgan",
    "Tabriz",
    "Semnan",
    "Yazd",
    "Rasht",
    "Arak",
    "Boshruyeh",
    "Mehran",
    "Dargaz",
    "Chabahar",
    "Zahedan",
    "Birjand",
    "Sanandaj",
    "Ahvaz",
    "Saravan",
    "Hamadan",
    "Khorramabad",
    "Qomsheh",
    "Ilam",
    "Sari",
    "Qazvin",
    "Bandar-e-Abbas",
    "Bandar-e Bushehr",
    "Sirjan",
    "Kashmar",
    "Bojnurd",
    "Qom",
    "Urmia",
    "Khvoy",
    "Yasuj",
]

CITIES_MIDDLE_EAST: list[str] = [
    "Istanbul",
    "Khartoum",
    "Cairo",
    "Luxor",
    "Ankara",
    "Beirut",
    "Aleppo",
    "Medina",
    "Makkah",
    "Djibouti",
    "Sanaa",
    "Irbil",
    "Baghdad",
    "Riyadh",
    "Kuwait City",
    "Baku",
    "Tehran",
    "Doha",
    "Dubai",
    "Kerman",
    "Muscat",
    "Mashhad",
    "Karachi",
    "Kabul",
]

CITIES_NORTH_AMERICA: list[str] = [
    "Honolulu",
    "Vancouver",
    "Edmonton",
    "Calgary",
    "Winnipeg",
    "Thunder Bay",
    "Toronto",
    "Montréal",
    "Halifax",
    "St. John's",
    "Portland",
    "San Francisco",
    "Los Angeles",
    "Billings",
    "Albuquerque",
    "Denver",
    "Kansas City",
    "Dallas",
    "Houston",
    "Minneapolis",
    "Chicago",
    "Orlando",
    "Atlanta",
    "Miami",
    "Washington,  D.C.",
    "Boston",
    "Hermosillo",
    "Monterrey",
    "Mexico City",
    "Mérida",
    "Havana",
    "Kingston",
]

CITIES_EUROPE: list[str] = [
    "Lisbon",
    "Dublin",
    "Madrid",
    "Edinburgh",
    "London",
    "Barcelona",
    "Paris",
    "Amsterdam",
    "Zürich",
    "Oslo",
    "Rome",
    "København",
    "Venice",
    "Berlin",
    "Vienna",
    "Stockholm",
    "Sarajevo",
    "Warsaw",
    "Athens",
    "Riga",
    "Bucharest",
    "Minsk",
    "Istanbul",
    "Kyiv",
    "Ankara",
    "Moscow",
    "Rostov",
    "Tbilisi",
]

REGION_COORDINATES: dict[str, tuple[float, float, float, float]] = {
    "WORLD": (-179.0, 180.0, -61.0, 61.0),
    "WORLD_FULL": (-179.0, 180.0, -89.0, 90.0),
    "NORTH_AMERICA": (-170.0, -40.0, 15.0, 61.0),
    "EUROPE": (-15.0, 50.0, 34.0, 61.0),
    "MIDDLE_EAST": (25.0, 75.0, 10.0, 45.0),
    "IRAN": (43.5, 63.5, 24.5, 40.0),
}

REGION_CITIES: dict[str, list[str]] = {
    "WORLD": CITIES_WORLD,
    "WORLD_FULL": CITIES_WORLD,
    "NORTH_AMERICA": CITIES_NORTH_AMERICA,
    "EUROPE": CITIES_EUROPE,
    "MIDDLE_EAST": CITIES_MIDDLE_EAST,
    "IRAN": CITIES_IRAN,
}

