name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build source distribution (sdist)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install build
          python -m build --sdist --outdir dist

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_WINDOWS: auto
          PYTHONUTF8: 1

      - name: Move wheels to dist folder
        run: |
          mkdir -p dist
          cp wheelhouse/*.whl dist/ || true

      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ github.run_id }}
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-wheels-ubuntu-latest-${{ github.run_id }}
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: built-wheels-windows-latest-${{ github.run_id }}
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: built-wheels-macos-latest-${{ github.run_id }}
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
